# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'g:\root\my_life\sbme_2025\3rd_year\second_semester\sports\Final Project\Project_Rana\project_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1556, 916)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1556, 916))
        MainWindow.setMaximumSize(QtCore.QSize(1556, 916))
        MainWindow.setStyleSheet("QMainWindow {\n"
"    border-image: url(:/images/Images/field.png) 0 0 0 0 stretch stretch;\n"
"}\n"
"QLabel {\n"
"    border: 1px solid rgb(36, 59, 34, 0);\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(191, 225, 158, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    color: rgb(36, 59, 34);\n"
"}\n"
"QGroupBox {\n"
"    background-color: rgba(255, 255, 255, 140);\n"
"    border: 1px solid rgba(0, 0, 0, 0);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QToolButton {\n"
"    background-color: rgba(255, 255, 255, 150);\n"
"    border: 1px solid rgba(0, 0, 0, 0);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0\n"
"    rgba(226, 129, 118, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    border: 1px solid rgba(0, 0, 0, 0);\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(161, 70, 59);\n"
"}\n"
"QPushButton:pressed {\n"
"    border: 4px solid rgb(161, 70, 59);\n"
"}\n"
"\n"
"\n"
"QSlider {\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0\n"
"    rgba(191, 225, 158, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    padding: 7px;\n"
"    border: 1px solid rgba(0, 0, 0, 0);\n"
"    border-radius: 10px;\n"
"}\n"
"QSlider::groove:horizontal {\n"
"    height: 6px;\n"
"    background-color: rgb(53, 86, 50);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background: rgb(255,255,255);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(200, 200, 200);\n"
"    width: 12px;\n"
"    hight: 6px;\n"
"    margin: -5px 0px;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::handle:horizontal:hover{\n"
"    width: 11px;\n"
"    border: 2px solid rgb(53, 86, 50);\n"
"}\n"
"QSlider::add-page:horizontal {\n"
"    background-color: rgb(230, 230, 230);\n"
"}\n"
"QSlider::sub-page:horizontal {\n"
"    background-color: rgb(53, 86, 50);\n"
"}\n"
"\n"
"QGraphicsView {\n"
"    border-image: url(:/images/Images/athlete_stages.png)  0 0 0 0 stretch stretch;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.plotWidget = QtWidgets.QWidget(self.centralwidget)
        self.plotWidget.setAutoFillBackground(False)
        self.plotWidget.setStyleSheet("border: 1px solid rgba(0, 0, 0, 0);\n"
"border-radius: 15px;\n"
"padding: 0px;\n"
"color: white;")
        self.plotWidget.setObjectName("plotWidget")
        self.gridLayout_12.addWidget(self.plotWidget, 0, 1, 1, 1)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        spacerItem = QtWidgets.QSpacerItem(20, 90, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_11.addItem(spacerItem, 2, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(281, 361))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 400))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem1, 0, 0, 1, 1)
        self.pushButton_play_pause = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_play_pause.sizePolicy().hasHeightForWidth())
        self.pushButton_play_pause.setSizePolicy(sizePolicy)
        self.pushButton_play_pause.setMinimumSize(QtCore.QSize(75, 40))
        self.pushButton_play_pause.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_play_pause.setStyleSheet("")
        self.pushButton_play_pause.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/play_pause_red.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_play_pause.setIcon(icon)
        self.pushButton_play_pause.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_play_pause.setObjectName("pushButton_play_pause")
        self.gridLayout_8.addWidget(self.pushButton_play_pause, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem2, 0, 3, 1, 1)
        self.pushButton_restart = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_restart.setMinimumSize(QtCore.QSize(75, 40))
        self.pushButton_restart.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_restart.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/restart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_restart.setIcon(icon1)
        self.pushButton_restart.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_restart.setObjectName("pushButton_restart")
        self.gridLayout_8.addWidget(self.pushButton_restart, 0, 2, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setHorizontalSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.toolButton_2 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_2.setEnabled(False)
        self.toolButton_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/slow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/icons/slow.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon2)
        self.toolButton_2.setIconSize(QtCore.QSize(40, 40))
        self.toolButton_2.setObjectName("toolButton_2")
        self.gridLayout_7.addWidget(self.toolButton_2, 0, 0, 1, 1)
        self.horizontalSlider_display_speed = QtWidgets.QSlider(self.groupBox)
        self.horizontalSlider_display_speed.setMinimumSize(QtCore.QSize(150, 45))
        self.horizontalSlider_display_speed.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalSlider_display_speed.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_display_speed.setObjectName("horizontalSlider_display_speed")
        self.gridLayout_7.addWidget(self.horizontalSlider_display_speed, 0, 1, 1, 1)
        self.toolButton = QtWidgets.QToolButton(self.groupBox)
        self.toolButton.setEnabled(False)
        self.toolButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/fast.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/icons/fast.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon3)
        self.toolButton.setIconSize(QtCore.QSize(40, 40))
        self.toolButton.setObjectName("toolButton")
        self.gridLayout_7.addWidget(self.toolButton, 0, 2, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_7, 1, 0, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setVerticalSpacing(2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(250, 40))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("border: 1px solid rgba(0, 0, 0, 0);\n"
"border-radius: 10px;\n"
"background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(185, 143, 102, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(77, 60, 43);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setHorizontalSpacing(2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_firing_angle = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_firing_angle.sizePolicy().hasHeightForWidth())
        self.label_firing_angle.setSizePolicy(sizePolicy)
        self.label_firing_angle.setMinimumSize(QtCore.QSize(80, 38))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_firing_angle.setFont(font)
        self.label_firing_angle.setStyleSheet("border: 1px solid rgb(36, 59, 34, 0);\n"
"border-radius: 10px;\n"
"background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(191, 225, 158, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(36, 59, 34);")
        self.label_firing_angle.setAlignment(QtCore.Qt.AlignCenter)
        self.label_firing_angle.setObjectName("label_firing_angle")
        self.gridLayout_3.addWidget(self.label_firing_angle, 0, 1, 1, 1)
        self.horizontalSlider_firing_angle = QtWidgets.QSlider(self.groupBox)
        self.horizontalSlider_firing_angle.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalSlider_firing_angle.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_firing_angle.setObjectName("horizontalSlider_firing_angle")
        self.gridLayout_3.addWidget(self.horizontalSlider_firing_angle, 0, 0, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.gridLayout_5.setRowStretch(1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_5, 1, 0, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setVerticalSpacing(2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(250, 40))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border: 1px solid rgba(0, 0, 0, 0);\n"
"border-radius: 10px;\n"
"background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(185, 143, 102, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(77, 60, 43);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 0, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setHorizontalSpacing(2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_launching_speed = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_launching_speed.sizePolicy().hasHeightForWidth())
        self.label_launching_speed.setSizePolicy(sizePolicy)
        self.label_launching_speed.setMinimumSize(QtCore.QSize(80, 38))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_launching_speed.setFont(font)
        self.label_launching_speed.setStyleSheet("border: 1px solid rgb(36, 59, 34, 0);\n"
"border-radius: 10px;\n"
"background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(191, 225, 158, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(36, 59, 34);")
        self.label_launching_speed.setAlignment(QtCore.Qt.AlignCenter)
        self.label_launching_speed.setObjectName("label_launching_speed")
        self.gridLayout_4.addWidget(self.label_launching_speed, 0, 1, 1, 1)
        self.horizontalSlider_launching_speed = QtWidgets.QSlider(self.groupBox)
        self.horizontalSlider_launching_speed.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalSlider_launching_speed.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_launching_speed.setObjectName("horizontalSlider_launching_speed")
        self.gridLayout_4.addWidget(self.horizontalSlider_launching_speed, 0, 0, 1, 1)
        self.gridLayout_4.setColumnStretch(0, 1)
        self.gridLayout_6.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        self.gridLayout_6.setRowStretch(1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_6, 2, 0, 1, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setVerticalSpacing(2)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_max_height = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_max_height.sizePolicy().hasHeightForWidth())
        self.label_max_height.setSizePolicy(sizePolicy)
        self.label_max_height.setMinimumSize(QtCore.QSize(130, 40))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_max_height.setFont(font)
        self.label_max_height.setStyleSheet("")
        self.label_max_height.setAlignment(QtCore.Qt.AlignCenter)
        self.label_max_height.setObjectName("label_max_height")
        self.gridLayout_15.addWidget(self.label_max_height, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(144, 40))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("border: 1px solid rgba(0, 0, 0, 0);\n"
"border-radius: 10px;\n"
"background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(185, 143, 102, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(77, 60, 43);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_15.addWidget(self.label_6, 0, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_15, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setVerticalSpacing(2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_throwing_distance = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_throwing_distance.sizePolicy().hasHeightForWidth())
        self.label_throwing_distance.setSizePolicy(sizePolicy)
        self.label_throwing_distance.setMinimumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_throwing_distance.setFont(font)
        self.label_throwing_distance.setStyleSheet("")
        self.label_throwing_distance.setAlignment(QtCore.Qt.AlignCenter)
        self.label_throwing_distance.setObjectName("label_throwing_distance")
        self.gridLayout_2.addWidget(self.label_throwing_distance, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border: 1px solid rgba(0, 0, 0, 0);\n"
"border-radius: 10px;\n"
"background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(185, 143, 102, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(77, 60, 43);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("border: 1px solid rgba(0, 0, 0, 0);\n"
"border-radius: 10px;\n"
"background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(185, 143, 102, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(77, 60, 43);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_throwing_time = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_throwing_time.sizePolicy().hasHeightForWidth())
        self.label_throwing_time.setSizePolicy(sizePolicy)
        self.label_throwing_time.setMinimumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_throwing_time.setFont(font)
        self.label_throwing_time.setStyleSheet("")
        self.label_throwing_time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_throwing_time.setObjectName("label_throwing_time")
        self.gridLayout.addWidget(self.label_throwing_time, 1, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout, 0, 2, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_10, 3, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox, 0, 0, 1, 1)
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setEnabled(False)
        self.graphicsView.setMinimumSize(QtCore.QSize(0, 200))
        self.graphicsView.setMaximumSize(QtCore.QSize(16777215, 300))
        self.graphicsView.setStyleSheet("")
        self.graphicsView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.graphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView.setInteractive(False)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_11.addWidget(self.graphicsView, 1, 0, 1, 1)
        self.gridLayout_11.setRowStretch(1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_11, 0, 0, 1, 1)
        self.gridLayout_12.setColumnStretch(0, 2)
        self.gridLayout_12.setColumnStretch(1, 5)
        self.gridLayout_13.addLayout(self.gridLayout_12, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"color: white;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_13.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_13.setRowStretch(1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_13, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1556, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_play_pause.setToolTip(_translate("MainWindow", "Play/Pause"))
        self.pushButton_restart.setToolTip(_translate("MainWindow", "Restart"))
        self.horizontalSlider_display_speed.setToolTip(_translate("MainWindow", "Playing speed"))
        self.label_5.setText(_translate("MainWindow", "Firing Angle"))
        self.label_firing_angle.setText(_translate("MainWindow", "0"))
        self.horizontalSlider_firing_angle.setToolTip(_translate("MainWindow", "Firing angle"))
        self.label_4.setText(_translate("MainWindow", "Launching Speed"))
        self.label_launching_speed.setText(_translate("MainWindow", "0"))
        self.horizontalSlider_launching_speed.setToolTip(_translate("MainWindow", "Launching speed"))
        self.label_max_height.setToolTip(_translate("MainWindow", "Maximum hight reached"))
        self.label_max_height.setText(_translate("MainWindow", "0"))
        self.label_6.setText(_translate("MainWindow", "Max. Height"))
        self.label_throwing_distance.setToolTip(_translate("MainWindow", "Throwing total distance"))
        self.label_throwing_distance.setText(_translate("MainWindow", "0"))
        self.label_3.setText(_translate("MainWindow", "Distance"))
        self.label_8.setText(_translate("MainWindow", "Time"))
        self.label_throwing_time.setToolTip(_translate("MainWindow", "Throwing total time"))
        self.label_throwing_time.setText(_translate("MainWindow", "0"))
        self.label.setText(_translate("MainWindow", "Throw Best Game"))
import icons_rc
import images_rc
